CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(254) NOT NULL
);

CREATE TABLE video (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(20) NOT NULL UNIQUE,
    user INT NOT NULL,
    upload_date DATETIME NULL,
    conversion_state BOOLEAN DEFAULT FALSE
);

ALTER TABLE video
ADD CONSTRAINT fk_user
FOREIGN KEY (user)
REFERENCES user(id)
ON DELETE CASCADE
ON UPDATE CASCADE;



CREATE TABLE user (id INT AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(100) NOT NULL UNIQUE, password VARCHAR(254) NOT NULL);
CREATE TABLE video (id INT AUTO_INCREMENT PRIMARY KEY, filename VARCHAR(20) NOT NULL UNIQUE, user INT NOT NULL, upload_date DATETIME NULL, conversion_state BOOLEAN DEFAULT FALSE);
ALTER TABLE video ADD CONSTRAINT fk_user FOREIGN KEY (user) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE;
